baseURL = 'https://example.com/'
languageCode = 'zh-CN'
title = '站点标题'
theme = 'totvan-theme'

[pagination]
  pagerSize = 20

summaryLength = '20' # <- 20 words are approximately 160 characters
googleAnalytics = '' # <- Your GA-4
disqusShortname = '' # <- Get form here : https://disqus.com

# URL结构 - 匹配WordPress的URL格式
[permalinks]
  posts = "/:year/:month/:day/:slug/"

# 启用分类和标签支持
[taxonomies]
  category = "categories"
  # tag = "tags"  # 禁用标签页面生成，保留文章meta标签用于SEO

# Sitemap配置
[sitemap]
  changefreq = "weekly"
  priority = 0.7
  filename = "sitemap.xml"

# 自定义输出格式配置（简化版）
[outputs]
  home = ["HTML"]

# 性能优化配置
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true

  [minify.tdewolff]
    [minify.tdewolff.css]
      keepCSS2 = true
      precision = 0
    [minify.tdewolff.html]
      keepComments = false
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepWhitespace = false
    [minify.tdewolff.js]
      keepVarNames = false
      noNullishOperator = false

# 缓存配置
[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "10m"
  [caches.getcsv]
    dir = ":cacheDir/:project"
    maxAge = "10m"
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = "720h"
  [caches.assets]
    dir = ":resourceDir/_gen"
    maxAge = "720h"
  [caches.modules]
    dir = ":cacheDir/modules"
    maxAge = "10m"

# 图片处理配置
[imaging]
  resampleFilter = "CatmullRom"
  quality = 85
  anchor = "smart"

[params]
  # Meta description, not exceeding 160 characters, used for the meta description within the HTML head
  description = '你的网站描述'
  mainSections = 'posts'

  # Logo 配置
  [params.logo]
    url = "/images/logo.png"  # 推荐使用相对路径
    width = 60
    height = 60
    alt = "网站 Logo"

  # Header广告配置
  [params.headerAd]
    enabled = false  # 设置为 true 启用 Header 广告
    text = "欢迎访问我们的广告商!"  # 广告文字
    targetUrl = "https://example.com/"  # 广告链接

  # Google AdSense配置
  [params.adsense]
    enable = false  # 设置为 true 启用 AdSense
    client = "ca-pub-xxxxxx"
    sidebar_slot = "xxxxxx"
    article_slot = "xxxxxx"

  [params.author]
    name = '作者名称'
    bio = '作者简介'
    avatar = '/images/avatar.jpg'
    twitter = ''

[menu] # Menu management
  [[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 15
  # [[menu.main]]
  # name = 'Tags'
  # pageRef = '/tags'
  # weight = 20
  [[menu.main]]
    name = 'Privacy Policy'
    pageRef = '/privacy-policy'
    weight = 25
  [[menu.main]]
    name = 'Cookie Policy'
    pageRef = '/cookie-policy'
    weight = 30
  [[menu.main]]
    name = 'Disclaimer'
    pageRef = '/disclaimer'
    weight = 35
  [[menu.main]]
    name = 'Terms of Service'
    pageRef = '/terms-of-service'
    weight = 40

  # Footer Menu
  [[menu.footer]]
    name = 'Privacy Policy'
    pageRef = '/privacy-policy'
    weight = 10
  [[menu.footer]]
    name = 'Terms of Service'
    pageRef = '/terms-of-service'
    weight = 20
  [[menu.footer]]
    name = 'Contact'
    url = 'mailto:contact@example.com'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [[module.mounts]]
    source = 'assets'
    target = 'static'
  [[module.mounts]]
    source = 'static'
    target = 'static'
